name: Deploy to Heroku

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: envvars
        run: |
          if [ ${GITHUB_EVENT_NAME} == "pull_request" ]; then
            GITHUB_SHA=${{ github.event.pull_request.head.sha }}
          fi
          echo ${{ github.event.pull_request.head.sha }}
          echo ${GITHUB_SHA}

      # - name: Deploy to Heroku
      #   env:
      #     HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      #   run: >-
      #     git push -f https://heroku:${HEROKU_API_TOKEN}@git.heroku.com/${HEROKU_APP_NAME}.git
      #     ${GITHUB_SHA}:main
